Bg 24753 zec consensus branch id rebase 1.7.1
BitGo/bitgo-utxo-lib pull request #90
Opened 2020-10-16 16:56 UTC by matthewzipkin-bitgo

https://github.com/BitGo/bitgo-utxo-lib/pull/89 but rebased on v1.7.1

2020-10-20 22:33 UTC, argjv reviewed
Update package.json version and LGTM

2020-10-20 22:38 UTC, matthewzipkin-bitgo commented
Ok thanks - still making sure it runs correctly as a dep to wallet-platform. Once I'm confident it works I'll come back and merge. Also should we call this version `1.7.1`? My concern is if its required using `^` then some package that isn't ready (doesn't have consensus ID set) will pull it down anyway -- but we already have a `1.8.x` and `1.9.x` I think. So...?

2020-10-26 13:51 UTC, OttoAllmendinger approved these changes
so this only affects how we are building new zcash txs, not how existing ones are parsed?

2020-10-26 13:51 UTC, OttoAllmendinger commented on test/fixtures/README.md
> +# Generate test vectors for new ZCash testnet consensus branch IDs
awesome!

long-term we should have a script for this, but we can tackle that when we overhaul this lib

2020-10-26 13:54 UTC, OttoAllmendinger commented
the fact that this changes the default way zcash transactions are built actually suggests we bump the minor version

Alternatively we could instead release a version of this lib that *supports* the new consensusBranchId in a convenient way without defaulting to it. That way we can decide at the callsite somehow.

2020-10-26 15:20 UTC, OttoAllmendinger requested changes
Actually I realized that this is for an old version. New development should happen on the master branch.

2020-10-26 15:29 UTC, argjv commented
We are releasing 1.7.2 because the latest version in master breaks platform and other places. Fixing utxo-lib is not in the roadmap.

2020-10-26 15:31 UTC, merged